name: mstudy
description: Find study spaces at the University of Michigan, Ann Arbor
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  string_similarity: ^2.0.0
  time_range_picker: ^2.1.0
  freezed_annotation:
  google_fonts: ^2.3.1
  json_api: ^5.0.5
  collection: ^1.15.0
  shared_preferences: ^2.0.13
  json_serializable: ^6.1.5
  flutter_native_splash: ^2.1.3+1
  geolocator: ^8.2.0
  map_launcher: ^2.2.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  freezed:
  flutter_launcher_icons: "^0.9.2"
  flutter_launcher_name:
    git:
      url: https://github.com/AlienKevin/flutter_launcher_name
      ref: "0.11.1"
  test:

flutter:
  uses-material-design: false
  fonts:
    - family: MaterialIconsSelected
      fonts:
        - asset: fonts/MaterialIconsSelected.ttf
  assets:
    - assets/

flutter_native_splash:
  color: "00274C"
  image: "assets/icon_512.png"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_512.png"

flutter_launcher_name:
  name: "MStudy"
